#!/usr/bin/env bash
# Installs and configures nginx on an Ubuntu server to serve "Holberton School"

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
